Algoritmo "Problema_Crescente"
Var
   X, Y : inteiro
Inicio
      escreval("Digite dois numeros:")
      leia(x)
      leia(y)
      enquanto x <> y faca
               se x < y entao
                  escreval("CRESCENTE!")
               senao
                    escreval("DECRECENTE!")
               fimse
      Escreval("Digite outros dois numeros:")
      leia(x)
      leia(y)
      fimenquanto
Fimalgoritmo