Algoritmo "Problema Idades"

Var
   n1, n2 : caractere
   i1, i2 : inteiro
   m : real
Inicio
   escreva("Nome da primeira pessoa: ")
   leia(n1)
   escreva("Idade da primeira pessoa: ")
   leia(i1)
   escreva("Nome da segunda pessoa: ")
   leia(n2)
   escreva("Idade da segunda pessoa: ")
   leia(i2)
   m <- (i2 + i1) / 2
   escreva("A idade média de ", n1, " e ", n2, " é de ", m:1:1, " anos.")


Fimalgoritmo